# Generated by Django 4.2.5 on 2023-09-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_todomodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='description_en',
            field=models.TextField(default='write here', null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='description_ru',
            field=models.TextField(default='write here', null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='description_uz',
            field=models.TextField(default='write here', null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='todo_name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='todo_name_ru',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='todo_name_uz',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
